#!/usr/bin/python3
"""Fail-closed, raw-object repository-policy checks.

This module is deliberately usable by local hooks and by the base-trusted PR
workflow.  Hooks are advisory: authorization for policy-surface changes comes
only from an exact manifest supplied by the trusted base checkout.
"""
from __future__ import annotations

import base64
import json
import os
import re
import stat
import subprocess
import sys
from pathlib import Path
from typing import Iterable

GIT = "/usr/bin/git"
PYTHON = "/usr/bin/python3"
ZERO = "0" * 40
CANONICAL_REPOSITORY = "Muminur/whisperspree"
CANONICAL_ORIGIN = b"https://github.com/Muminur/whisperspree.git"
EXCEPTION_MANIFEST = b".repo-policy-secret-exceptions.json"
MAX_EVENT_BYTES = 1024 * 1024
MAX_POLICY_INPUT_BYTES = 64 * 1024
MAX_BLOB_BYTES = 1024 * 1024
OID_RE = re.compile(r"^[0-9a-fA-F]+$")
HOOK_INDEX_FILE: str | None = None
SECRET = re.compile(
    rb"(?:"
    rb"(?:[\"']?(?:api[_-]?key|secret|token|password)[\"']?\s*[:=]\s*[\"']?[^\s\"']+)"
    rb"|(?:authorization\s*:\s*bearer\s+[^\s\x00]+)"
    rb"|sk-(?:ant-|proj-|svcacct-)|gh[pousr]_|github_pat_|BEGIN [A-Z ]*PRIVATE KEY"
    rb"|AKIA[A-Z0-9]{16}|xox[baprs]-[A-Za-z0-9-]{20,}|AIza[A-Za-z0-9_-]{35}"
    rb"|eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{16,}"
    rb"|https?://[^\s/:]+:[^\s@/]+@|[A-Za-z0-9+/]{48,}={1,2}"
    rb"|\b[A-Z]+_TOKEN_[A-Z0-9_]{8,})",
    re.I,
)
ATTRIBUTION = re.compile(rb"Claude|Codex|OpenAI|AI-generated|AI-assisted|generated by|Co-authored-by:|\xf0\x9f\xa4\x96|(^|[^A-Za-z0-9_])AI([^A-Za-z0-9_]|$)", re.I)


class PolicyError(Exception):
    pass


def fail(message: str, code: int = 1) -> int:
    print(message, file=sys.stderr)
    return code


def minimal_env() -> dict[str, str]:
    """Do not pass caller controlled loader, Git, proxy, or shell state on."""
    return {
        "PATH": "/usr/bin:/bin",
        "HOME": "/var/empty",
        "LC_ALL": "C",
        "LANG": "C",
        "GIT_CONFIG_NOSYSTEM": "1",
        "GIT_CONFIG_GLOBAL": "/dev/null",
        "GIT_TERMINAL_PROMPT": "0",
    }


def hostile_environment() -> bool:
    forbidden = {"PYTHONPATH", "PYTHONHOME", "PYTHONSTARTUP", "BASH_ENV", "ENV", "ZDOTDIR", "LD_PRELOAD", "DYLD_INSERT_LIBRARIES"}
    for name, value in os.environ.items():
        if name in forbidden or name.startswith("GIT_"):
            if name in {"GIT_CONFIG_GLOBAL", "GIT_CONFIG_NOSYSTEM", "GIT_TERMINAL_PROMPT"} and value in {"/dev/null", "1", "0"}:
                continue
            if name == "GIT_INDEX_FILE" and value == HOOK_INDEX_FILE:
                continue
            return True
    return False


def hook_index_file(root_text: str) -> str | None:
    """Accept Git's default index only while the installed pre-commit hook runs."""
    value = os.environ.get("GIT_INDEX_FILE")
    if value is None:
        return None
    if not value or "\0" in value:
        raise PolicyError("unsafe policy environment")
    root = Path(root_text).resolve()
    try:
        result = subprocess.run(
            [GIT, "-C", os.fspath(root), "rev-parse", "--git-path", "index"],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            env=minimal_env(),
            check=False,
            timeout=30,
        )
        if result.returncode:
            raise OSError
        expected_text = result.stdout.decode("utf-8", "strict").strip()
        expected = Path(expected_text)
        if not expected.is_absolute():
            expected = root / expected
        supplied = Path(value)
        if not supplied.is_absolute():
            supplied = root / supplied
        expected_info = expected.lstat()
        supplied_info = supplied.lstat()
    except (OSError, UnicodeError, subprocess.TimeoutExpired) as error:
        raise PolicyError("unsafe policy environment") from error
    if (
        expected.resolve() != supplied.resolve()
        or stat.S_ISLNK(expected_info.st_mode)
        or stat.S_ISLNK(supplied_info.st_mode)
        or not stat.S_ISREG(expected_info.st_mode)
        or not stat.S_ISREG(supplied_info.st_mode)
    ):
        raise PolicyError("unsafe policy environment")
    return value


def run_git(root: Path, *args: str, data: bytes | None = None) -> bytes:
    if hostile_environment():
        raise PolicyError("unsafe policy environment")
    try:
        result = subprocess.run([GIT, "-C", os.fspath(root), *args], input=data, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, env=minimal_env(), check=False, timeout=30)
    except (OSError, subprocess.TimeoutExpired) as error:
        raise PolicyError("Git plumbing unavailable") from error
    if result.returncode:
        raise PolicyError("Git plumbing failed")
    return result.stdout


def json_no_duplicates(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON key")
        result[key] = value
    return result


def parse_json(data: bytes, message: str) -> object:
    try:
        return json.loads(data.decode("utf-8"), object_pairs_hook=json_no_duplicates)
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as error:
        raise PolicyError(message) from error


def worktree(root_text: str, allowed_hooks_path: Path | None = None) -> Path:
    root = Path(root_text).resolve()
    if not root.is_dir():
        raise PolicyError("repository root must be a Git worktree")
    top = Path(run_git(root, "rev-parse", "--show-toplevel").decode("utf-8", "strict").strip()).resolve()
    if root != top:
        raise PolicyError("repository root must be the worktree top level")
    reject_unsafe_git_config(root, allowed_hooks_path)
    return root


def object_size(root: Path) -> int:
    fmt = run_git(root, "rev-parse", "--show-object-format").decode("ascii", "strict").strip()
    if fmt == "sha1":
        return 40
    if fmt == "sha256":
        return 64
    raise PolicyError("unsupported Git object format")


def oid(value: object, size: int) -> str:
    if not isinstance(value, str) or len(value) != size or not OID_RE.fullmatch(value):
        raise PolicyError("invalid event object identifier")
    return value.lower()


def commit(root: Path, value: object, size: int) -> str:
    result = oid(value, size)
    run_git(root, "cat-file", "-e", result + "^{commit}")
    return result


def reject_unsafe_git_config(root: Path, allowed_hooks_path: Path | None = None) -> None:
    """Read origin/scope in a NUL-safe form and reject controlling config."""
    raw = run_git(root, "config", "--null", "--show-origin", "--show-scope", "--list")
    # Git emits scope<TAB>origin<TAB>key\nvalue\0.  Values are never trusted;
    # policy decisions only need the case-folded key plus credential exception.
    allowed = {"core.repositoryformatversion", "core.filemode", "core.bare", "core.logallrefupdates", "core.ignorecase", "core.precomposeunicode", "user.name", "user.email", "remote.origin.url", "remote.origin.fetch", "branch.main.remote", "branch.main.merge"}
    fields = raw.split(b"\0")
    if fields and fields[-1] == b"":
        fields.pop()
    if len(fields) % 3:
        raise PolicyError("Git configuration unavailable")
    for index in range(0, len(fields), 3):
        try:
            _scope, _origin, pair = fields[index:index + 3]
            key_raw, value = pair.split(b"\n", 1)
            key = key_raw.decode("ascii", "strict").lower()
        except (UnicodeDecodeError, ValueError) as error:
            raise PolicyError("Git configuration unavailable") from error
        if key == "credential.helper" and value == b"osxkeychain":
            continue
        if key == "core.hookspath" and allowed_hooks_path is not None:
            try:
                configured_hooks = Path(value.decode("utf-8", "strict"))
                configured_info = configured_hooks.lstat()
                expected_info = allowed_hooks_path.lstat()
            except (OSError, UnicodeError) as error:
                raise PolicyError("unsafe Git configuration") from error
            if (
                configured_hooks == allowed_hooks_path
                and configured_hooks.is_absolute()
                and stat.S_ISDIR(configured_info.st_mode)
                and not stat.S_ISLNK(configured_info.st_mode)
                and stat.S_ISDIR(expected_info.st_mode)
                and not stat.S_ISLNK(expected_info.st_mode)
            ):
                continue
        if key in allowed or (key.startswith("branch.") and key.endswith((".remote", ".merge"))):
            continue
        # No include, rewrite, transport, hooks, diff/textconv, TLS/proxy/header,
        # fsmonitor, helper, or unknown config is permitted to influence policy.
        raise PolicyError("unsafe Git configuration")


def parse_raw(raw: bytes, oid_len: int) -> list[tuple[bytes, str, str, str, str, str]]:
    fields, records, index = raw.split(b"\0"), [], 0
    while index + 1 < len(fields) and fields[index]:
        header, path = fields[index], fields[index + 1]
        try:
            metadata, status = header[1:].rsplit(b" ", 1)
            old_mode, new_mode, old_oid, new_oid = metadata.split(b" ")
            status_text = status[:1].decode("ascii")
        except (UnicodeDecodeError, ValueError) as error:
            raise PolicyError("malformed raw Git record") from error
        for value in (old_oid, new_oid):
            if len(value) != oid_len or not OID_RE.fullmatch(value.decode("ascii", "strict")):
                raise PolicyError("invalid object identifier")
        if not re.fullmatch(rb"[0-7]{6}", old_mode) or not re.fullmatch(rb"[0-7]{6}", new_mode) or status_text not in {"A", "M", "D", "T"}:
            raise PolicyError("malformed raw Git record")
        records.append((path, status_text, old_mode.decode(), old_oid.decode().lower(), new_mode.decode(), new_oid.decode().lower()))
        index += 2
    if index != len(fields) - 1:
        raise PolicyError("malformed raw Git record")
    return records


def raw_diff(root: Path, *revisions: str) -> list[tuple[bytes, str, str, str, str, str]]:
    return parse_raw(run_git(root, "diff", "--raw", "-z", "--no-renames", "--no-abbrev", "--no-ext-diff", "--no-textconv", *revisions), object_size(root))


def root_changes(root: Path, revision: str) -> list[tuple[bytes, str, str, str, str, str]]:
    return parse_raw(run_git(root, "diff-tree", "-r", "--root", "--no-commit-id", "--raw", "-z", "--no-renames", "--no-abbrev", "--no-ext-diff", "--no-textconv", revision), object_size(root))


def index_changes(root: Path) -> list[tuple[bytes, str, str, str, str, str]]:
    return parse_raw(run_git(root, "diff", "--cached", "--raw", "-z", "--no-renames", "--no-abbrev", "--no-ext-diff", "--no-textconv"), object_size(root))


def staged_index(root: Path) -> None:
    """Reject an absent or substituted index instead of scanning an empty view."""
    index_text = run_git(root, "rev-parse", "--git-path", "index").decode("utf-8", "strict").strip()
    index = Path(index_text)
    if not index.is_absolute():
        index = root / index
    try:
        info = index.lstat()
    except OSError as error:
        raise PolicyError("staged index unavailable") from error
    if not stat.S_ISREG(info.st_mode) or stat.S_ISLNK(info.st_mode):
        raise PolicyError("staged index unavailable")


def read_blob(root: Path, blob: str) -> bytes:
    size = run_git(root, "cat-file", "-s", blob).decode("ascii", "strict").strip()
    if not size.isdigit() or int(size) > MAX_BLOB_BYTES:
        raise PolicyError("policy input exceeds size limit")
    return run_git(root, "cat-file", "blob", blob)


def policy_path(path: bytes) -> bool:
    return path.startswith(b"scripts/") or path.startswith(b".githooks/") or path.startswith(b".github/workflows/") or path == EXCEPTION_MANIFEST or path == b".codex/rules/default.rules" or path == b".codex/config.toml" or path.startswith(b".codex/agents/") or path == b".gitignore"


def governance_or_environment_path(path: bytes) -> bool:
    parts, name = path.split(b"/"), path.rsplit(b"/", 1)[-1].lower()
    return name in {b"agents.md", b"claude.md", b"planning.md", b"tasks.md", b"prd.md", b"loop.md", b"idea.txt"} or path.lower() == b"docs/prd.md" or any(part.lower() == b".env" or part.lower().startswith(b".env.") for part in parts)


def scan_entries(root: Path, entries: Iterable[tuple[bytes, str, str]], exceptions: set[tuple[bytes, str, str, str]] | None = None, transitions: set[tuple[bytes, str, str, str, str, str]] | None = None) -> None:
    failures = False
    for path, mode, blob in entries:
        if governance_or_environment_path(path):
            failures = True
        try:
            content = read_blob(root, blob)
        except PolicyError:
            raise
        if SECRET.search(content) and (exceptions is None or (path, mode, blob, "token") not in exceptions):
            failures = True
    if transitions is not None:
        for path, status, old_mode, old_oid, new_mode, new_oid in transitions:
            if policy_path(path) and (path, status, old_mode, old_oid, new_mode, new_oid) not in transitions:
                failures = True
    if failures:
        raise PolicyError("policy rejected repository object")


def introduced_commits(root: Path, before: str | None, after: str) -> Iterable[str]:
    args = ("rev-list", "--topo-order", after) if before is None else ("rev-list", "--topo-order", f"{before}..{after}")
    try:
        process = subprocess.Popen([GIT, "-C", os.fspath(root), *args], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, env=minimal_env())
    except OSError as error:
        raise PolicyError("Git plumbing unavailable") from error
    assert process.stdout is not None
    try:
        for line in process.stdout:
            value = line.strip().decode("ascii", "strict")
            if not OID_RE.fullmatch(value):
                raise PolicyError("Git plumbing failed")
            yield value.lower()
    finally:
        process.stdout.close()
    if process.wait(timeout=30) != 0:
        raise PolicyError("Git plumbing failed")


def commit_entries(root: Path, revision: str) -> Iterable[tuple[bytes, str, str]]:
    raw = run_git(root, "diff-tree", "-r", "--root", "-m", "--no-commit-id", "--raw", "-z", "--no-renames", "--no-abbrev", "--no-ext-diff", "--no-textconv", revision)
    for path, status, _old_mode, _old_oid, mode, blob in parse_raw(raw, object_size(root)):
        if status != "D":
            yield path, mode, blob


def event_json(path_text: str) -> dict[str, object]:
    path = Path(path_text)
    try:
        info = path.lstat()
        if not stat.S_ISREG(info.st_mode) or stat.S_ISLNK(info.st_mode) or info.st_size > MAX_EVENT_BYTES:
            raise OSError
        data = path.read_bytes()
    except OSError as error:
        raise PolicyError("event payload must be a regular JSON object") from error
    value = parse_json(data, "event payload must be a regular JSON object")
    if type(value) is not dict:
        raise PolicyError("event payload must be a JSON object")
    return value


def parse_secret_exceptions(doc: object, oid_len: int) -> set[tuple[bytes, str, str, str]]:
    if not isinstance(doc, list):
        raise PolicyError("malformed trusted manifest")
    result: set[tuple[bytes, str, str, str]] = set()
    for item in doc:
        if not isinstance(item, dict) or set(item) != {"path_b64", "mode", "oid", "rule"}:
            raise PolicyError("malformed trusted manifest")
        try:
            path = base64.b64decode(item["path_b64"], validate=True)
        except (TypeError, ValueError) as error:
            raise PolicyError("malformed trusted manifest") from error
        if not path or b"\0" in path or not isinstance(item["mode"], str) or not re.fullmatch(r"[0-7]{6}", item["mode"]) or item["rule"] != "token":
            raise PolicyError("malformed trusted manifest")
        result.add((path, item["mode"], oid(item["oid"], oid_len), "token"))
    return result


def parse_transitions(doc: object, oid_len: int) -> set[tuple[bytes, str, str, str, str, str]]:
    if not isinstance(doc, list):
        raise PolicyError("malformed trusted manifest")
    result: set[tuple[bytes, str, str, str, str, str]] = set()
    for item in doc:
        required = {"path_b64", "status", "old_mode", "old_oid", "new_mode", "new_oid"}
        if not isinstance(item, dict) or set(item) != required:
            raise PolicyError("malformed trusted manifest")
        try:
            path = base64.b64decode(item["path_b64"], validate=True)
        except (TypeError, ValueError) as error:
            raise PolicyError("malformed trusted manifest") from error
        status = item["status"]
        if not path or b"\0" in path or status not in {"A", "M", "D"} or not all(isinstance(item[key], str) and re.fullmatch(r"[0-7]{6}", item[key]) for key in ("old_mode", "new_mode")):
            raise PolicyError("malformed trusted manifest")
        old_oid, new_oid = oid(item["old_oid"], oid_len), oid(item["new_oid"], oid_len)
        zero_mode = "000000"
        if (status == "A" and (item["old_mode"] != zero_mode or old_oid != "0" * oid_len)) or (status == "D" and (item["new_mode"] != zero_mode or new_oid != "0" * oid_len)):
            raise PolicyError("malformed trusted manifest")
        if status in {"A", "M"} and new_oid == "0" * oid_len:
            raise PolicyError("malformed trusted manifest")
        if status == "M" and old_oid == "0" * oid_len:
            raise PolicyError("malformed trusted manifest")
        result.add((path, status, item["old_mode"], old_oid, item["new_mode"], new_oid))
    return result


def trusted_manifest(path_text: str, oid_len: int) -> tuple[set[tuple[bytes, str, str, str]], set[tuple[bytes, str, str, str, str, str]]]:
    path = Path(path_text)
    try:
        data = path.read_bytes()
    except OSError as error:
        raise PolicyError("trusted manifest unavailable") from error
    doc = parse_json(data, "malformed trusted manifest")
    if not isinstance(doc, dict) or set(doc) != {"version", "secret_exceptions", "policy_transitions"} or doc["version"] != 2:
        raise PolicyError("malformed trusted manifest")
    return parse_secret_exceptions(doc["secret_exceptions"], oid_len), parse_transitions(doc["policy_transitions"], oid_len)


def legacy_exceptions(path_text: str, oid_len: int) -> set[tuple[bytes, str, str, str]]:
    try:
        doc = parse_json(Path(path_text).read_bytes(), "malformed exception manifest")
    except OSError as error:
        raise PolicyError("malformed exception manifest") from error
    if not isinstance(doc, dict) or set(doc) != {"version", "exceptions"} or doc["version"] != 1:
        raise PolicyError("malformed exception manifest")
    return parse_secret_exceptions(doc["exceptions"], oid_len)


def fetch_pr_objects(root: Path, event: dict[str, object], base: str, head: str, number: int, clone_url: object) -> None:
    if not isinstance(clone_url, str) or not clone_url:
        raise PolicyError("pull request head unavailable")
    isolated = f"refs/whisperspree-policy/pr/{number}"
    try:
        result = subprocess.run([GIT, "-C", os.fspath(root), "fetch", "--no-tags", "--no-recurse-submodules", clone_url, f"refs/pull/{number}/head:{isolated}"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, env=minimal_env(), timeout=30, check=False)
    except (OSError, subprocess.TimeoutExpired) as error:
        raise PolicyError("pull request fetch failed") from error
    if result.returncode:
        raise PolicyError("pull request fetch failed")
    fetched = commit(root, run_git(root, "rev-parse", isolated).decode("ascii", "strict").strip(), object_size(root))
    if fetched != head:
        raise PolicyError("pull request head mismatch")


def check_transitions(changes: list[tuple[bytes, str, str, str, str, str]], trusted: set[tuple[bytes, str, str, str, str, str]]) -> None:
    policy_changes = [change for change in changes if policy_path(change[0])]
    if not policy_changes:
        return
    manifest_changes = [change for change in policy_changes if change[0] == EXCEPTION_MANIFEST]
    non_manifest = [change for change in policy_changes if change[0] != EXCEPTION_MANIFEST]
    if manifest_changes:
        # A manifest-only PR is the constrained, non-recursive preauthorization
        # anchor. It may not authorize another policy change in its own PR.
        if non_manifest or len(manifest_changes) != 1:
            raise PolicyError("policy transition is not trusted")
        return
    if any(change not in trusted for change in policy_changes):
        raise PolicyError("policy transition is not trusted")


def ci_scan(event_name: str, event_path: str, root_text: str, manifest_kind: str | None, manifest_path: str | None) -> int:
    try:
        root, size, event = worktree(root_text), None, event_json(event_path)
        size = object_size(root)
        exceptions: set[tuple[bytes, str, str, str]] = set()
        transitions: set[tuple[bytes, str, str, str, str, str]] = set()
        if manifest_kind == "trusted":
            assert manifest_path is not None
            exceptions, transitions = trusted_manifest(manifest_path, size)
        elif manifest_kind == "exceptions":
            assert manifest_path is not None
            exceptions = legacy_exceptions(manifest_path, size)
        if event_name == "pull_request":
            pull = event.get("pull_request")
            if not isinstance(pull, dict) or not isinstance(pull.get("base"), dict) or not isinstance(pull.get("head"), dict):
                raise PolicyError("invalid pull request event")
            before, after = commit(root, pull["base"].get("sha"), size), oid(pull["head"].get("sha"), size)
            repository = event.get("repository")
            if repository is not None:
                if not isinstance(repository, dict) or repository.get("full_name") != CANONICAL_REPOSITORY or not isinstance(pull.get("number"), int):
                    raise PolicyError("invalid pull request event")
                checked = commit(root, run_git(root, "rev-parse", "HEAD").decode("ascii", "strict").strip(), size)
                if checked != before:
                    raise PolicyError("pull request base is not trusted")
                head_repo = pull["head"].get("repo")
                clone_url = head_repo.get("clone_url") if isinstance(head_repo, dict) else None
                try:
                    commit(root, after, size)
                except PolicyError:
                    fetch_pr_objects(root, event, before, after, pull["number"], clone_url)
            else:
                try:
                    commit(root, after, size)
                    ancestor = run_git(root, "merge-base", "--is-ancestor", before, after)
                    del ancestor
                except PolicyError:
                    checked = commit(root, run_git(root, "rev-parse", "HEAD").decode("ascii", "strict").strip(), size)
                    if before != checked:
                        raise PolicyError("pull request base is not the checked-out trusted revision")
                    before = run_git(root, "merge-base", before, after).decode("ascii", "strict").strip()
        elif event_name == "push":
            before, after, ref = oid(event.get("before"), size), oid(event.get("after"), size), event.get("ref")
            if not isinstance(ref, str) or not (ref.startswith("refs/heads/") or ref.startswith("refs/tags/")) or after == "0" * size:
                raise PolicyError("invalid push event")
            target = commit(root, run_git(root, "rev-parse", after + "^{}").decode("ascii", "strict").strip(), size)
            if before == "0" * size:
                before = None
            else:
                before = commit(root, before, size)
                run_git(root, "merge-base", "--is-ancestor", before, target)
            after = target
        else:
            raise PolicyError("unsupported event name")
        all_entries: list[tuple[bytes, str, str]] = []
        for revision in introduced_commits(root, before, after):
            all_entries.extend(commit_entries(root, revision))
        changes = [] if before is None else raw_diff(root, before, after)
        if before is None:
            changes = raw_diff(root, f"{after}^{{tree}}") if False else []
        check_transitions(changes, transitions)
        scan_entries(root, all_entries, exceptions)
        return 0
    except PolicyError as error:
        return fail(str(error))


def staged_check(root_text: str, *, from_pre_commit_hook: bool = False) -> int:
    global HOOK_INDEX_FILE
    try:
        if from_pre_commit_hook:
            HOOK_INDEX_FILE = hook_index_file(root_text)
        hook_path = Path(__file__).resolve().parent.parent / ".githooks" if from_pre_commit_hook else None
        root = worktree(root_text, hook_path)
        staged_index(root)
        changes = index_changes(root)
        if any(governance_or_environment_path(path) or policy_path(path) for path, *_rest in changes):
            raise PolicyError("staged policy rejected a protected path")
        entries = [(path, mode, blob) for path, status, _old_mode, _old_oid, mode, blob in changes if status != "D"]
        scan_entries(root, entries)
        return 0
    except (OSError, UnicodeError, PolicyError) as error:
        return fail(str(error))
    finally:
        HOOK_INDEX_FILE = None


def attribution(path_text: str) -> int:
    try:
        path = Path(path_text)
        info = path.lstat()
        if not stat.S_ISREG(info.st_mode) or stat.S_ISLNK(info.st_mode):
            raise PolicyError("secure policy input unavailable")
        if ATTRIBUTION.search(path.read_bytes()):
            raise PolicyError("forbidden attribution language found in metadata")
        return 0
    except (OSError, PolicyError) as error:
        return fail(str(error), 2)


def pre_push(script_root_text: str, payload: bytes) -> int:
    try:
        script_root = Path(script_root_text).resolve()
        root = worktree(os.getcwd(), script_root / ".githooks")
        if len(payload) > MAX_POLICY_INPUT_BYTES:
            raise PolicyError("policy input exceeds size limit")
        records = payload.splitlines()
        if not records:
            raise PolicyError("pre-push input is empty")
        size = object_size(root)
        for record in records:
            try:
                _local_ref, local_oid, _remote_ref, remote_oid = record.decode("ascii", "strict").split()
            except ValueError as error:
                raise PolicyError("malformed pre-push input") from error
            if local_oid == "0" * size:
                raise PolicyError("push deletion is rejected")
            target = commit(root, run_git(root, "rev-parse", local_oid + "^{}").decode("ascii", "strict").strip(), size)
            before = None if remote_oid == "0" * size else commit(root, remote_oid, size)
            if before is not None:
                run_git(root, "merge-base", "--is-ancestor", before, target)
            entries: list[tuple[bytes, str, str]] = []
            for revision in introduced_commits(root, before, target):
                if ATTRIBUTION.search(run_git(root, "log", "-1", "--format=%B", revision)):
                    raise PolicyError("forbidden attribution language found in metadata")
                entries.extend(commit_entries(root, revision))
            changes = root_changes(root, target) if before is None else raw_diff(root, before, target)
            if any(policy_path(change[0]) for change in changes):
                raise PolicyError("policy transition is not trusted")
            scan_entries(root, entries)
        return 0
    except PolicyError as error:
        return fail(str(error))


def git_config_values(root: Path, key: str) -> list[bytes]:
    """Read an optional multi-value setting without inheriting caller config."""
    try:
        result = subprocess.run(
            [GIT, "-C", os.fspath(root), "config", "--null", "--get-all", key],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            env=minimal_env(),
            check=False,
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise PolicyError("Git configuration unavailable") from error
    if result.returncode == 1:
        return []
    if result.returncode != 0:
        raise PolicyError("Git configuration unavailable")
    values = result.stdout.split(b"\0")
    if not values or values[-1] != b"":
        raise PolicyError("Git configuration unavailable")
    return values[:-1]


def safe_push(script_root: str, check_only: bool, values: list[str]) -> int:
    try:
        if hostile_environment():
            raise PolicyError("unsafe policy environment")
        root = worktree(os.getcwd())
        expected_root = Path(script_root).resolve()
        if root != expected_root or not (expected_root / ".git").is_dir():
            raise PolicyError("safe push must run from its owning primary worktree")
        if len(values) != 2 or values[0] != "origin":
            raise PolicyError("safe push requires origin and one refspec")
        if git_config_values(root, "remote.origin.url") != [CANONICAL_ORIGIN] or git_config_values(root, "remote.origin.pushurl"):
            raise PolicyError("origin is not the canonical repository")
        branch = run_git(root, "symbolic-ref", "--quiet", "--short", "HEAD").decode().strip()
        if not re.fullmatch(r"milestone([0-9]+)/(?:t\1-[0-9]+-[a-z0-9][a-z0-9-]*|verification)", branch):
            raise PolicyError("current branch is not permitted")
        if values[1] not in {"HEAD", f"HEAD:refs/heads/{branch}"}:
            raise PolicyError("push destination must equal current branch")
        upstream_remote = git_config_values(root, f"branch.{branch}.remote")
        upstream_merge = git_config_values(root, f"branch.{branch}.merge")
        if bool(upstream_remote) != bool(upstream_merge) or (upstream_remote and (upstream_remote != [b"origin"] or upstream_merge != [f"refs/heads/{branch}".encode()])):
            raise PolicyError("upstream does not match the current branch")
        if check_only:
            return 0
        result = subprocess.run([GIT, "-C", os.fspath(root), "push", "origin", f"HEAD:refs/heads/{branch}"], env=minimal_env(), check=False)
        return result.returncode
    except PolicyError as error:
        return fail(str(error), 2)


def main(argv: list[str]) -> int:
    if not argv:
        return fail("missing policy action", 2)
    action, rest = argv[0], argv[1:]
    if action in {"staged", "staged-hook"} and len(rest) == 1:
        return staged_check(rest[0], from_pre_commit_hook=action == "staged-hook")
    if action == "attribution" and len(rest) == 1:
        return attribution(rest[0])
    if action == "pre-push" and len(rest) == 1:
        return pre_push(rest[0], sys.stdin.buffer.read())
    if action == "push" and len(rest) >= 2:
        return safe_push(rest[0], rest[1] == "1", rest[2:])
    if action == "ci" and len(rest) in {3, 5}:
        kind = None
        path = None
        if len(rest) == 5:
            if rest[3] == "--trusted-manifest":
                kind, path = "trusted", rest[4]
            elif rest[3] == "--exceptions":
                kind, path = "exceptions", rest[4]
            else:
                return fail("invalid policy invocation", 2)
        return ci_scan(rest[0], rest[1], rest[2], kind, path)
    return fail("invalid policy invocation", 2)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
